--- 

#-------------------------------------------------
# MQTT setting

MQTT_server:                # MQTT server name or IP
MQTT_port:                  # MQTT server port
MQTT_login:                 # MQTT server login
MQTT_password:              # MQTT server password
MQTT_base_topic: homesrv    # base topic
MQTT_disable:   True        # Disable writing to MQTT server - can be set to True for Debug purposes

MQTT_refesh:    300         # refresh info every N seconds

# enable / disable integrations
MQTT_enable_awido:   True
MQTT_enable_db:      True
MQTT_enable_weather: True
MQTT_enable_nina:    True


#-------------------------------------------------
# awido Waste

awido_region: ffb       # put your region code here
awido_title: Zuhause    # choose a title 
awido_oid: xxxxxxxxxxxx     # put your oid here 
awido_waste_types:                                  # restrict the data to the listed waste types
    - "Bioabfall"
    - "Restmülltonne 40-240 L"
    - "Papiertonne 4-wöchentlich"
    - "Wertstofftonne 80-1100 L"
#    - "Papiercontainer 2-wöchentlich"
#    - "Restmüllcontainer 660-1100 L"
    - "Problemmüll"


#-------------------------------------------------
# DButils

DB_client_id:      xxxxxx     # put you DB client id here
DB_client_secret:  xxxxxx     # put you DB client secret here

DB_stations:
    Pasing: 8004158            # list at least one station, using the format <Name>: <StationId>                 
#    München Hbf: 8000261
#    München Hbf Gl.27-36: 8098261
#    München Hbf Gl.5-10: 8098262
#    München Hbf (tief): 8098263

# Filter disruptions
DB_disruptions_authors:
DB_disruptions_states: 
    - BY
    - BW
DB_disruptions_withtxt: True

DB_refresh_schedule:    1800    # refresh interval from (main) schedule [seconds]
DB_refresh_changes:     30      # refreh interval for changes [seconds] (should be set >=30s)
DB_refresh_disruptions: 300     # refreh interval for disruptions [seconds]

DB_timetable_base_url:   https://apis.deutschebahn.com/db-api-marketplace/apis/timetables/v1/
DB_disruptions_base_url:   https://www.s-bahn-muenchen.de/.rest/verkehrsmeldungen?path=%2Faktuell


#-------------------------------------------------
# NINA

nina_location: xxxxxx    # Name of you city / location


#-------------------------------------------------
# openweathermap settings

weather_api_key: xxxxxx   # put your openweathermap api key here 
weather_lang:    de
weather_units:   metric

weather_locations:  # you can specify you locations here
    Mycity:          
        lat: 22.2222222
        lon: 11.1111111

# Texts - you can change them if you want
uv_index:
    0: "niedrig"         
    1: "mittel"
    2: "hoch"
    3: "sehr hoch"
    4: "extrem"

visibility:
    0: "extremer Nebel"
    1: "sehr starker Nebel"
    2: "starker Nebel"
    3: "Nebel"
    4: "leichter Nebel"
    5: "dunstig"
    6: "leicht diesig"
    7: "klar"

clouds:
    0:  "wolkenlos"
    1:  "sonnig"
    2:  "heiter"
    3:  "leicht bewölkt"
    4:  "wolkig"
    5:  "bewölkt"
    6:  "stark bewölkt"
    7:  "fast bedeckt"
    8:  "bedeckt"

daytime:
    7:  "Morgens"
    10: "Vormittags" 
    13: "Mittags"
    16: "Nachmittags" 
    19: "Abends" 
    23: "Nachts"

moonphase:
    0: "Neumond"
    1: "zunehmende Sichel"
    2: "zunehmender Halbmond"
    3: "zunehmender Mond"
    4: "Vollmond"
    5: "abnehmender Mond"
    6: "abnehmende Halbmond"
    7: "abnehmende Sichel"
    8: "Neumond"

precipitation:
    0: "kein"
    1: "leicht"
    2: "mäßig"
    3: "stark"
    4: "sehr stark"
    5: "extrem"

prec_forecast:
    prec_ends: "Niederschlag endet gegen {}"
    prec_starts: "Beginnender Niederschlag gegen {}" 
    prec_cont: "Anhaltender Niederschlag"
    prec_no: "Kein Niederschlag in Sicht"

